[project]
name = "sdm230device"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.8.20"
dependencies = [
    "pymodbus==2.3.0",
    "pyserial==3.4",
]
